# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require "motion/project/template/android"

Motion::Project::App.setup do |app|
  app.name = "Edit Text Sample"
  app.api_version = "L"
end
